# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161220_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
